### ISSUE TITLE
Investigate using a single kernel in integration tests

### ISSUE THREAD

**Issue by rbradford** [intel/cloud-hypervisor#100]
Currently we build two kernels in our integration tests. We should investigate if we can just build one kernel and use it for all the tests and see if that has a positive impact on our test run time. We're currently trending towards 30 minutes for a single test run.

**Comment by sboeuf** [comment]
Moving forward, I hope we can have only one kernel, once both virtio-pmem and virtio-fs gets merged upstream.

**Comment by rbradford** [comment]
Based on #107. Building the custom kernel is 1m9s for the checkout and 1m32s for the build. For a total of 2m41s approximately.

At 161s that is roughly the equivalent of running 3 of the tests (usually they report out at taking 50-60s before rebooting.)

This is probably not the right direction to be looking at for improving the CI time and instead should look at how to improve the individual test time and also run tests in parallel.
