### ISSUE TITLE
Add support for virtio-vsock

### ISSUE THREAD

**Issue by valliscooper** [intel/cloud-hypervisor#102]
To facillitate CH integration with the kata-runtime a vsock based communication path between the kata proxy running on the hypervisor host and the agent running inside the cloud hypervisor instance has to be supported. This implies virtio-vsock support in the cloud-hypervisor.

**Comment by sboeuf** [comment]
Working on porting the hybrid version from Firecracker.

**Comment by ericooper** [comment]
very good indeed. Thanks.
