### ISSUE TITLE
Investigate MSI related issue shown up by logs

### ISSUE THREAD

**Issue by rbradford** [intel/cloud-hypervisor#156]
`
cloud-hypervisor: 681.634076ms: WARN:vmm/src/vm.rs:1009 -- failed to deliver MSI message, blocked by guest
`

This appears when the firmware does virtio-block operations. It's doesn't use interrupts at all and instead is polling driven.

**Comment by sboeuf** [comment]
Thanks for reporting this, I'll take a look once I'm done with virtio-fs improvements.

**Comment by rbradford** [comment]
Are both halves fixed or only 2.) ?

**Comment by sboeuf** [comment]
2) is fixed for sure, but I'm not sure about 1)
Have you tried to reproduce with the patch?

**Comment by rbradford** [comment]
@sboeuf Yes, 1.) is still present.
