### ISSUE TITLE
CH seems to not boot at all when started with --console off AND --serial off

### ISSUE THREAD

**Issue by ericooper** [intel/cloud-hypervisor#192]
I've observed a few times that when starting CH with --console off and --serial off (and console hvc0 as only console related kernel parameter) CH cpu load goes to 100 % and the boot process is stuck somewhere. 

When repeating this with -vvv (debug)  results in thousands of 
``
cloud-hypervisor: 41.831058789s: DEBUG:vm-virtio/src/net.rs:377 -- RX_TAP_EVENT received 
``
being printed but monitoring the tap device simultaneously with tcpdump shows no packets related to CH at all. 

Kernel used for this test was a custom build 5.2 kernel with full virtio support build-in. 

CH used was a fresh debug build from master branch 

The combination --console tty serial off works as expected.

**Comment by rbradford** [comment]
Why are you specifying --console off and also putting "console=hvc0" in the kernel command line?

**Comment by ericooper** [comment]
I think when using an uefi root file system the kernel & the cmdline of the kernel is set by the boot entries on the uefi partition and not by the CH kernel cli parameter which seems to be ignored in that case or do you seen this differently? This can lead to this situation. Do you think this is simply unavoidable and a consequence of wrong usage of CH or could this scenario be prevented/checked somehow? I was just wondering whether we can avoid the 100% cpu utilization which seems to me a bit odd.

**Comment by rbradford** [comment]
If you specify the Linux kernel on the command line that is the kernel that will be loaded and that is the command line that will be used. Only if you use hypervisor-firmware and a full disk image will the bootloader come into force.

Does it boot fine / performance restored if you use "null" instead of "off" ?

**Comment by ericooper** [comment]
I'll check and try to better locate this. I am using indeed the firmware + uefi approach at the moment for different reasons and keep you posted in case I have more specific information.

**Comment by ericooper** [comment]
--console null indeed looks better again!

**Comment by rbradford** [comment]
@ericooper In which case the command line to CH is ignored and whatever in the bootloader files is used. They probably have console=ttyS0 which causes a very very slow boot when you have no serial enabled. This is why #164 was added.

**Comment by sboeuf** [comment]
In case you use CH with `hypervisor-fw`, the kernel command line included in ClearLinux images includes `console=ttyS0`, which means the kernel will try to use the serial PIO that are actually not handled by CH since we're not emulating the serial device (because you specified `--serial off`).
The whole issue is explained [here](https://github.com/intel/cloud-hypervisor/issues/163#issue-478636916).

We can close this issue as there is no bug here, the summary is that you cannot use `--serial off` if the kernel command line specifies `console=ttyS0`.

**Comment by ericooper** [comment]
I actually do not use a clear image but use my own image without serial kernel command line option: only hvc0. I do understand that the CH executable can't check or take responsibility for how the kernel finally is booted in case the command line comes from the disk partition but I'm still a bit worried about the 100% CPU consumption and the thousands of RX tap receive events. Could it be that the kernel picks  by mistake the virtio net device as console in case CH doesn't offer a virtio console?

**Comment by sboeuf** [comment]
Oh I see, sorry I didn't follow this issue from the beginning. I'll reopen it so that we can try to investigate when we get some spare time!

**Comment by ericooper** [comment]
I've been applying the perf tool in order to better trace this. It's not perfect but at least shows something like a hotspot in the virtio_net epoll handler causing the 100% CPU utilization I guess:

```
Samples: 34K of event 'cpu-clock', Event count (approx.): 34877631957
  Children      Self  Command          Shared Object       Symbol
+   93.08%     0.00%  virtio_net       [unknown]           [.] 0xffffffffffffffff
+   93.08%     0.00%  virtio_net       cloud-hypervisor    [.] std::sys_common::backtrace::__rust_begin_short_backtrace
+   93.08%     0.00%  virtio_net       cloud-hypervisor    [.] _$LT$vm_virtio..net..Net$u20$as$u20$vm_virtio..device..VirtioDevice$GT$::activate::_$u7b$$u7b$closure$u7d$$u7d
+   93.08%     1.43%  virtio_net       cloud-hypervisor    [.] vm_virtio::net::NetEpollHandler::run
+   86.25%     0.37%  virtio_net       cloud-hypervisor    [.] epoll::wait
+   85.88%    38.90%  virtio_net       libc-2.28.so        [.] epoll_wait
+   44.15%     0.00%  virtio_net       [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+   44.15%    19.91%  virtio_net       [kernel.kallsyms]   [k] do_syscall_64
+   24.23%     1.53%  virtio_net       [kernel.kallsyms]   [k] __x64_sys_epoll_wait
+   22.70%     1.62%  virtio_net       [kernel.kallsyms]   [k] do_epoll_wait
+   16.30%     2.42%  virtio_net       [kernel.kallsyms]   [k] ep_poll
+   13.83%     3.83%  virtio_net       [kernel.kallsyms]   [k] ep_scan_ready_list.constprop.22
+    7.03%     1.08%  virtio_net       [kernel.kallsyms]   [k] ep_send_events_proc
+    6.45%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] __rust_maybe_catch_panic
+    6.44%     0.00%  cloud-hyperviso  libc-2.28.so        [.] __GI___clone (inlined)
+    6.44%     0.00%  cloud-hyperviso  libpthread-2.28.so  [.] start_thread
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::sys::unix::thread::Thread::new::thread_start
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::sys_common::thread::start_thread (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h8a416d1da8d3f01e
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h0a4386b5b5aafdff (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::panic::catch_unwind (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::panicking::try (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::panicking::try::do_call
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7025df1a30
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] std::sys_common::backtrace::__rust_begin_short_backtrace
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] vmm::vm::Vm::start::_$u7b$$u7b$closure$u7d$$u7d$::hc6283eda47d7bc24 (inlined)
+    6.44%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] vmm::vm::Vcpu::run
+    6.43%     0.00%  cloud-hyperviso  libc-2.28.so        [.] __ioctl (inlined)
+    6.43%     0.01%  cloud-hyperviso  cloud-hypervisor    [.] kvm_ioctls::ioctls::vcpu::VcpuFd::run
+    6.42%     0.00%  cloud-hyperviso  cloud-hypervisor    [.] kvm_ioctls::sys_ioctl::ioctl (inlined)
+    5.65%     0.43%  virtio_net       [kernel.kallsyms]   [k] ep_item_poll.isra.16
+    5.40%     0.46%  virtio_net       cloud-hypervisor    [.] vm_virtio::net::NetEpollHandler::rx_single_frame
+    5.22%     4.29%  virtio_net       [kernel.kallsyms]   [k] tun_chr_poll
+    4.62%     1.06%  virtio_net       cloud-hypervisor    [.] vm_virtio::queue::Queue::iter
+    3.36%     0.65%  virtio_net       [kernel.kallsyms]   [k] __fget_light
+    3.32%     0.00%  virtio_net       cloud-hypervisor    [.] vm_memory::bytes::Bytes::read_obj (inlined)
+    3.18%     1.22%  virtio_net       cloud-hypervisor    [.] vm_memory::guest_memory::<impl vm_memory::bytes::Bytes<vm_memory::guest_memory::GuestAddress> for T>::read_sli
+    2.76%     0.00%  virtio_net       cloud-hypervisor    [.] vm_memory::guest_memory::<impl vm_memory::bytes::Bytes<vm_memory::guest_memory::GuestAddress> for T>::read (in
+    2.76%     0.00%  virtio_net       cloud-hypervisor    [.] vm_memory::guest_memory::GuestMemory::try_access (inlined)
+    2.71%     2.71%  virtio_net       [kernel.kallsyms]   [k] __fget
+    1.87%     1.65%  virtio_net       [kernel.kallsyms]   [k] mutex_lock
+    1.51%     0.00%  virtio_net       cloud-hypervisor    [.] vm_memory::guest_memory::_$LT$impl$u20$vm_memory..bytes..Bytes$LT$vm_memory..guest_memory..GuestAddress$GT$$u2
+    1.39%     1.39%  virtio_net       libc-2.28.so        [.] __libc_enable_asynccancel
```

**Comment by rbradford** [comment]
There is a bug in the virtio-net poll handling that I am looking at however it is unrelated to anything to do with the console/serial configuration. See #208 for the work to address this issue.
