### ISSUE TITLE
how to logout vm with cmd line or keyboard shortcut

### ISSUE THREAD

**Issue by Apokleos** [intel/cloud-hypervisor#206]
Hi
I have running a VM according to the official guide with clearlinux， and I can enter the system successfully. 
But  I have no idea how to quit/logout the VM with keyboard shortcuts or some special command lines.
Is there some description for operating  in CLOUDH Environment?

Thx!!!

**Comment by sboeuf** [comment]
Hi @Apokleos, since we don't have ACPI shutdown/reboot implemented yet, the only way to shutdown the VM is to issue the following command:
```bash
$ sudo reboot
```
The reboot has the effect to trigger a write on the emulated port IO (8042 device), which the VMM interpret as a shutdown.

**Comment by Apokleos** [comment]
@sboeuf 
Yeah, it does work for me.
Thank you.
/close

**Comment by sboeuf** [comment]
Great :+1:
