### ISSUE TITLE
Busy loop spinning in virtio-net thread

### ISSUE THREAD

**Issue by rbradford** [intel/cloud-hypervisor#208]
This is observed if you just enable network with CH. (CH appears in top with 100% CPU.)

We keep getting woken up because there is something to read on the tap device and then do not read it as we think we shouldn't.

**Comment by rbradford** [comment]
The CPU usage disappears once the network interface is brought up inside the guess. The issue is that the queue runs out of available descriptors so stops reading from the TAP device which then means the epoll_wait keeps returning.

When the network interface is brought up in the guest, the packets are then consumed resulting in available descriptors becoming available resulting in the CPU load returning to normal.

**Comment by rbradford** [comment]
CC @ericooper

**Comment by sboeuf** [comment]
@rbradford very nice finding :+1:

**Comment by ericooper** [comment]
@rbradford very good indeed. thanks.
