### ISSUE TITLE
Implement a TAP based vhost-user-net backend

### ISSUE THREAD

**Issue by sameo** [intel/cloud-hypervisor#242]
The current virtio implementation relies on a TAP interface for sending and receiving packets to and from the kernel. This is currently implemented in the virtio-net device itself. For example, when the guest tries to send a networking packet through its virtio networking interface, the virtio-net device reads it from the virtio Tx queue and then writes it to the TAP interface.

For vhost-user-net implementation we want to do 2 things:

1. Switch our default virtio device implementation to be vhost-user based (a.k.a. vhost-user-net). The virtio-net device implementation won't be the default one anymore.

2. Have our virtio device implementation talk through the vhost-user socket to a TAP based backend, which is different from the ovs+dpdk setup you're describing here. The TAP based backend will be a separate process, and there will be one TAP based vhost-user-net backend process per networking device per guest. For example, if we launch a cloud-hypervisor guest with 2 virtio networking interfaces, we will end up launching 2 vhost-user-net backend processes for that particular guest, each of those processes will handle its own TAP interface. It is up to the host admin to decide what to do with those TAP interfaces: They could be bridged together or not, but this is outside of cloud-hypervisor's scope.

For 2, we could re-use some existing implementation (Like the QEMU test one), but we prefer to implement our own backend, in Rust.

**Comment by bonzini** [comment]
It would be great to have a vhost-user-net backend that is also a reference implementation for vhost-user-rs!

**Comment by sboeuf** [comment]
@bonzini is `vhost-user-rs` the rust-vmm crate https://github.com/rust-vmm/vhost ?
FYI, we have under development an equivalent of `libvhost-user` with the PR #276 
And this wrapper basically relies on the `vhost` crate from rust-vmm (even if not totally true for now since the code is not there yet on rust-vmm).
On top of this, anybody should be able to implement their own backend (net, blk, virtio-fs, etc...)

**Comment by bonzini** [comment]
See jiangliu/vhostuser_rs, I don't think it's been formally proposed as a rust-vmm crate because @jiangliu wanted to combine vhost-user and vhost-kernel into a unified rust-vmm/vhost crate.

**Comment by sboeuf** [comment]
Oh yeah we're talking about the same one then. The crate from Jiang Liu is great as it fully implements the vhost-user protocol. But we wanted to have some common code (like libvhost-user) to handle together the virtqueues and the vhost-user interaction through the socket.

**Comment by bonzini** [comment]
Should that also be part of rust-vmm/vhost? Possibly through a feature flag.

**Comment by jiangliu** [comment]
> See jiangliu/vhostuser_rs, I don't think it's been formally proposed as a rust-vmm crate because @jiangliu wanted to combine vhost-user and vhost-kernel into a unified rust-vmm/vhost crate.

I have posted the latest implementation of vhost crate at https://github.com/rust-vmm/vhost/pull/2 , which implements both vhost-user and vhost-kernel, also includes some fixes from cloud-hypervisor.

**Comment by sboeuf** [comment]
@bonzini that's a good question. I think the feature flag is the best way to go since it will allow users to avoid pulling the virtqueue specific part if they don't want to use it.
Also this makes sense, as having a separate crate for this libvhost-user code would be a bit too much since the amount of code is really not that big.

**Comment by sboeuf** [comment]
@jiangliu great!

**Comment by jiangliu** [comment]
We have also developed a test suite for vhost-user spec, that's another space for cooperation. But some comments are in Chinese:(

**Comment by sboeuf** [comment]
@jiangliu can you point us to this code? I definitely don't want us to duplicate efforts.

**Comment by jiangliu** [comment]
It hasn't been posted to public yet, but I do think this is an area for cooperation.

**Comment by jiangliu** [comment]
Suggest to merge the PR  https://github.com/rust-vmm/vhost/pull/2 first, then we could cooperate to improve it with better doc and tests.

**Comment by sboeuf** [comment]
>It hasn't been posted to public yet, but I do think this is an area for cooperation.

Oh I see! Do you think you could have the people who worked on it looking at #276 to provide some comments?

>Suggest to merge the PR rust-vmm/vhost#2 first, then we could cooperate to improve it with better doc and tests.

Sounds good.

**Comment by sameo** [comment]
Fixed with commit f6d1a9d9
