### ISSUE TITLE
can't boot in host kernel 4.4.161

### ISSUE THREAD

**Issue by terenceli** [intel/cloud-hypervisor#258]
Hello,
I can't boot with the main page's example in a host 4.4.1651 kernel. I didn't see any host kernel required, so I open issue.
Using top -H -p $pid, I got following output.

top - 19:25:49 up  8:13,  1 user,  load average: 0.23, 0.35, 0.67
Threads:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.9 us,  2.7 sy,  0.0 ni, 86.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4093376 total,   363312 free,  1521620 used,  2208444 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  2294196 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                               
 10259 root      20   0 1275088   7848   7124 R 99.9  0.2   0:12.64 vcpu0                                                                                                                                                 
 10272 root      20   0 1275088   7848   7124 S 32.3  0.2   0:05.33 virtio_blk                                                                                                                                            
 10250 root      20   0 1275088   7848   7124 S  0.0  0.2   0:00.04 cloud-hyperviso                                                                                                                                       
 10263 root      20   0 1275088   7848   7124 S  0.0  0.2   0:00.00 signal_handler                                                                                                                                        

The perf of the cloud-hypervisor:

    53.76%     0.00%  vcpu0       libc-2.27.so        [.] 0xffff80d4392b95d7                        
                 |
                 ---0x1165d7
                    |          
                    |--41.08%-- entry_SYSCALL_64_fastpath
                    |          sys_ioctl
                    |          do_vfs_ioctl
                    |          kvm_vcpu_ioctl
                    |          |          
                    |          |--40.51%-- kvm_arch_vcpu_ioctl_run
                    |          |          |          
                    |          |          |--16.56%-- vmx_handle_exit
                    |          |          |          |          
                    |          |          |           --16.44%-- handle_ept_misconfig
                    |          |          |                     |          
                    |          |          |                     |--15.92%-- kvm_io_bus_write
                    |          |          |                     |          |          
                    |          |          |                     |          |--15.55%-- __kvm_io_bus_write
                    |          |          |                     |          |          |          
                    |          |          |                     |          |          |--14.24%-- ioeventfd_write
                    |          |          |                     |          |          |          |          
                    |          |          |                     |          |          |          |--13.98%-- eventfd_signal
                    |          |          |                     |          |          |          |          |          
                    |          |          |                     |          |          |          |          |--13.79%-- __wake_up_locked_key
                    |          |          |                     |          |          |          |          |          |          
                    |          |          |                     |          |          |          |          |          |--13.53%-- __wake_up_common
                    |          |          |                     |          |          |          |          |          |          |          
                    |          |          |                     |          |          |          |          |          |           --13.41%-- ep_poll_callback
                    |          |          |                     |          |          |          |          |          |                     |          
                    |          |          |                     |          |          |          |          |          |                     |--12.77%-- __wake_up_locked
                    |          |          |                     |          |          |          |          |          |                     |          |          
                    |          |          |                     |          |          |          |          |          |                     |          |--12.70%-- __wake_up_common
                    |          |          |                     |          |          |          |          |          |                     |          |          |          
                    |          |          |                     |          |          |          |          |          |                     |          |           --12.26%-- default_wa

After the hang, set debug point in 'process_queue', we can see there are lots of calling of 'process_queue' but the virtio-blk queue is empty.

Any ideas?

Thanks,
Li Qiang

**Comment by rbradford** [comment]
Please give the console output and the full command line you used to invoke cloud-hypervisor.

**Comment by terenceli** [comment]
@rbradford All of the output is following:

root@ubuntu:~/cloud-hypervisor/target/debug# ./cloud-hypervisor --kernel ./hypervisor-fw --disk ./clear-29160-kvm.img --cpus 1 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng
Cloud Hypervisor Guest
	vCPUs: 1
	Memory: 1024 MB
	Kernel: "./hypervisor-fw"
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: "./clear-29160-kvm.img" }])

**Comment by sameo** [comment]
@terenceli Trying to reproduce that on top of a Fedora host kernel, I can't. Are you running this with Ubuntu as a host?

**Comment by terenceli** [comment]
@sameo No, once upon a time I just compile myself 4.4.161 kernel（at that time, this is the 4.4 stable tree）, so I test this on that. Maybe we can test current 4.4 table tree 4.4.191?

**Comment by sameo** [comment]
@terenceli Yes, we should try. Can you also please run with the `-vvv` option and paste the console output here?

**Comment by terenceli** [comment]
@sameo 
root@ubuntu:~/cloud-hypervisor/target/debug#  ./cloud-hypervisor --kernel ./hypervisor-fw --disk ./clear-29160-kvm.img --cpus 1 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng -vvv
Cloud Hypervisor Guest
	vCPUs: 1
	Memory: 1024 MB
	Kernel: "./hypervisor-fw"
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: "./clear-29160-kvm.img" }])
cloud-hypervisor: 199.013121ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 199.521948ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 199.556309ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 199.596152ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 199.611291ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 199.653639ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 199.694114ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 199.736245ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 199.775323ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 199.92018ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 199.992615ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 200.05336ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 200.130243ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 200.211762ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 200.258116ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 200.340709ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 200.483549ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x16
cloud-hypervisor: 200.60378ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x18
cloud-hypervisor: 200.702078ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x18
cloud-hypervisor: 200.810434ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x20
cloud-hypervisor: 200.863957ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x28
cloud-hypervisor: 200.957509ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x30
cloud-hypervisor: 201.03179ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x1c
cloud-hypervisor: 201.098402ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 201.127139ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 201.856939ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e
cloud-hypervisor: 202.088187ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e

**Comment by rbradford** [comment]
@terenceli add `--console off --serial tty` to your command line

**Comment by rbradford** [comment]
e.g. `./cloud-hypervisor --kernel ./hypervisor-fw  --console off --serial tty --disk ./clear-29160-kvm.img --cpus 1 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng -vvv`

**Comment by terenceli** [comment]
root@ubuntu:~/cloud-hypervisor/target/debug# ./cloud-hypervisor --kernel ./hypervisor-fw --console off --serial tty --disk ./clear-29160-kvm.img --cpus 1 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng -vvv
Cloud Hypervisor Guest
	vCPUs: 1
	Memory: 1024 MB
	Kernel: "./hypervisor-fw"
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: "./clear-29160-kvm.img" }])
Starting..
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace64 address=ffff80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Bar: type=Unused address=0
cloud-hypervisor: 33.765379ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 34.078373ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 34.168046ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 34.250238ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 34.283331ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 34.364702ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 34.427159ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 34.535353ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 34.619132ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 34.728646ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 34.828917ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 34.963995ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 35.074335ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 35.213373ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 35.273127ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 35.386518ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 35.494781ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x16
cloud-hypervisor: 35.601678ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x18
cloud-hypervisor: 35.709531ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x18
cloud-hypervisor: 35.808797ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x20
cloud-hypervisor: 35.908095ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x28
cloud-hypervisor: 36.003637ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x30
cloud-hypervisor: 36.131496ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x1c
cloud-hypervisor: 36.22253ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 36.283519ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
Virtio block device configured
cloud-hypervisor: 37.936011ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e
cloud-hypervisor: 38.187688ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e

**Comment by rbradford** [comment]
@terenceli try this firmware: https://github.com/intel/rust-hypervisor-firmware/releases/download/0.2.0/hypervisor-fw

**Comment by terenceli** [comment]
@rbradford almost the same:

root@ubuntu:~/cloud-hypervisor/target/debug# ./cloud-hypervisor --kernel ./another/hypervisor-fw --console off --serial tty --disk ./clear-29160-kvm.img --cpus 1 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng -vvv
Cloud Hypervisor Guest
	vCPUs: 1
	Memory: 1024 MB
	Kernel: "./another/hypervisor-fw"
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: "./clear-29160-kvm.img" }])
Starting..
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace64 address=ffff80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Bar: type=Unused address=0
cloud-hypervisor: 77.491694ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 77.853946ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 77.911107ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 77.99409ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 78.065047ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 78.189119ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 78.284549ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 78.385049ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x0
cloud-hypervisor: 78.482939ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:160 -- read_common_config_dword: offset 0x4
cloud-hypervisor: 78.562721ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 78.675906ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 78.751175ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0x8
cloud-hypervisor: 78.810132ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:187 -- write_common_config_dword: offset 0xc
cloud-hypervisor: 78.865227ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 78.901421ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
cloud-hypervisor: 78.983799ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 79.131011ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x16
cloud-hypervisor: 79.274985ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x18
cloud-hypervisor: 79.373203ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x18
cloud-hypervisor: 79.483962ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x20
cloud-hypervisor: 79.587439ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x28
cloud-hypervisor: 79.653243ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:227 -- write_common_config_qword: offset 0x30
cloud-hypervisor: 79.734836ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:146 -- write_common_config_word: offset 0x1c
cloud-hypervisor: 79.828939ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:100 -- read_common_config_byte: offset 0x14
cloud-hypervisor: 79.899104ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:113 -- write_common_config_byte: offset 0x14
Virtio block device configured. Capacity: 17893376 sectors
cloud-hypervisor: 82.670412ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e
cloud-hypervisor: 84.271029ms: DEBUG:vm-virtio/src/transport/pci_common_config.rs:123 -- read_common_config_word: offset 0x1e

**Comment by terenceli** [comment]
@rbradford It seems that using 0.2 version hypervisor firmware doesn't address this issue. I missed anything?

**Comment by rbradford** [comment]
Oh, I don't think it should be closed. I didn't realise that PR closed this. I'm guessing you're using Xenial as you've got an old kernel so I will try and create a VM running that and see if I can reproduce this issue.

**Comment by rbradford** [comment]
I used ccloudvm to create a xenial VM running the stock xenial 4.4.0-161-generic kernel. And I was able to follow the instructions and boot into an image. Is it possible you have a corrupted image? 

```
rob@artemis:~/Downloads$ sha1sum clear-29160-kvm.img.xz 
bf141c84e69d97fe2b4f9f2448ee5ec6c1d0041c  clear-29160-kvm.img.xz
rob@artemis:~/Downloads$ unxz clear-29160-kvm.img.xz 
rob@artemis:~/Downloads$ sha1sum clear-29160-kvm.img 
05e5b73caad327c26b8bc96ff020c55023341422  clear-29160-kvm.img

```

**Comment by terenceli** [comment]
@rbradford I don't think this is the issue. My system has several kernel version. Once it's in 4.15, it works as expected, But once reboot and it's in 4.4.161 it hangs. Could you please compile a separated alone kernel if you have a powerful server.

**Comment by rbradford** [comment]
@terenceli It works with the Ubuntu Xenial 4.4.0-161  kernel. If you've build your own kernel with your own configuration there is probably something missing. Do you need to continue to use this custom kernel?

**Comment by terenceli** [comment]
@rbradford In fact I'm just curious about what's the problem. It can boot qemu with no problem.

**Comment by rbradford** [comment]
If you care you'll need to bisect your kernel configuration against the stock Ubuntu one (which works) to find out which change in your personal configuration is needed. However that is out of scope for this project as a whole.
