### ISSUE TITLE
Address memory layout issues

### ISSUE THREAD

**Issue by rbradford** [intel/cloud-hypervisor#286]
Currently guest memory and devices all share the same 64GiB limit. This is bad as it limits the size of guest memory and what we can do with our devices. It would be nice to increase that possibly up to the 256TiB limit per 48-bit physical addresses.

Issues:

- [x] The firmware can't identity map that huge area in order to find the PCI bars for the virtio block device it wants to boot from. A logical solution would be to put the virtio block device in the 32-bit hole (see #285)
- [x] Currently the ACPI tables hardcode the range for devices from 32GiB upto 64GiB. It should instead use the top of RAM up to the end of the address space
- [x] Query host physical size
- [ ] Add some "big" tests to be run seperately on the CI - 64GiB guest memory, huge virtio-pmem, etc

Future:

- [ ] Preparing for hotplug of memory. My proposal here would be for us to reserve (maybe ask the user how much) a certain amount of address space above the current RAM. Then when we give "top of RAM" to the ACPI/E820 tables it is actually real_top_of_ram + reserved_for_hotplug_ram.

The big advantage of all this is we don't need to have a fixed size 64-bit device hole.

**Comment by sameo** [comment]
@rbradford 
> It would be nice to increase that possibly up to the 256TiB limit per 48-bit physical addresses.

48-bit is for the *virtual* address space, the physical one is smaller. Each CPU typically defines both its physical and virtual address space size, and this is readable through CPUID 0x80000008. `/proc/cpuinfo` is also displaying it under the `address sizes` entry. My Kaby Lake host provides 48 bits for the virtual address space and 39 for the physical one.

By default, the kernel uses 36 bits wide physical address spaces on 64-bit x86 hosts, unless it can read the above mentioned CPUID leave.

**Comment by rbradford** [comment]
I've learnt that you do not what to mark the device region or the hole as E820_RESERVED
