### ISSUE TITLE
Cloud Hypervisor control loop is bound to the VM lifecycle

### ISSUE THREAD

**Issue by sameo** [intel/cloud-hypervisor#303]
Currently, the main control loop is bound to the VM being started or not.
That works fine when we can only atomically create and start a VM from the `cloud-hypervisor` CLI, but if we want to asynchronously be able to control the whole VM lifecycle (from creation to shutdown) with e.g. an HTTP API, this is not flexible enough.

In order to support a more flexible architecture, we need to decouple the VMM control loop from the VM itself. For that we should have a single VMM thread that's running the main control loop. This thread always run and its control loop listens for both VM events (stdin, shutdown, reset, etc) and external events received through an internal, Rust `mpsc` channel based API. This API should allow for controlling the entire VM lifecycle.

As CLI parameters would be converted into internal API requests, the VMM control loop could be used by both the CLI and the future HTTP API.

**Comment by sameo** [comment]
cc @sboeuf @rbradford @chao-p

**Comment by chao-p** [comment]
Agree. This is basically VMM loop vs VM loop. There is an open that do we plan to support multiple VMs in one VMM? In another word, do we really want to intercept VM events (stdin, shutdown, reset, etc) triggered from guest in VMM loop as well?

**Comment by sameo** [comment]
> Agree. This is basically VMM loop vs VM loop. There is an open that do we plan to support multiple VMs in one VMM? In another word, do we really want to intercept VM events (stdin, shutdown, reset, etc) triggered from guest in VMM loop as well?

For now, I'd like to keep it simple and only support the VM <-> VMM bijection.
I think supporting multiple VMs per VMM is a bigger task than only adding a VM specific control loop, so it should be a task/effort of its own.
