### ISSUE TITLE
What's the purpose of setting the tss 

### ISSUE THREAD

**Issue by terenceli** [intel/cloud-hypervisor#305]
Hi, I want to know what's the purpose of setting the tss register in creating VM:

        fd.set_tss_address(arch::x86_64::layout::KVM_TSS_ADDRESS.raw_value() as usize)
            .map_err(Error::VmSetup)?;

BTW: I don't want to open an issue for this small question. but the slack channel in the main page is invalid. Is there a new slack channel to discuss like this issue?

Thanks

**Comment by rbradford** [comment]
This is needed when executing a vmlinux binary as the Linux assembly code to configure the TSS (and setup other things such as the GDT, long mode, etc) is not run when booting from the vmlinux.

https://elixir.bootlin.com/linux/latest/source/arch/x86/boot/compressed/head_64.S#L195

Notice that it jumps to `startup_64` (which is the entry point we use for vmlinux boots) shortly after configuring the TSS. Therefore `startup_64` expects the TSS to be configured and so we need to set it up.

**Comment by sameo** [comment]
> BTW: I don't want to open an issue for this small question. but the slack channel in the main page is invalid. Is there a new slack channel to discuss like this issue?

Could you please check if the new link from PR #306 works for you?

**Comment by terenceli** [comment]
@sameo Yes, it works!

**Comment by terenceli** [comment]
@rbradford as far as I can find, this set tss is to call ioctl(KVM_CAP_SET_TSS_ADDR). From the kernel doc:

4.36 KVM_SET_TSS_ADDR

Capability: KVM_CAP_SET_TSS_ADDR
Architectures: x86
Type: vm ioctl
Parameters: unsigned long tss_address (in)
Returns: 0 on success, -1 on error

This ioctl defines the physical address of a three-page region in the guest
physical address space.  The region must be within the first 4GB of the
guest physical address space and must not conflict with any memory slot
or any mmio address.  The guest may malfunction if it accesses this memory
region.

This ioctl is required on Intel-based hosts.  This is needed on Intel hardware
because of a quirk in the virtualization implementation (see the internals
documentation when it pops into existence).

From Paolo's answer here:
-->https://lwn.net/Articles/658736/
He said this ioctl is used for 'unrestricted_guest=0'.  
As the cloud-hypervisor direct start in 'startup_64', it is in long mode. so I think we don't need this ioctl(KVM_CAP_SET_TSS_ADDR). (I comment out the code, and it still works both for vmlinux.bin or for the rust firmware cases).

I'm still confused by this ioctl. could you provide more infomation, such as 'internals
documentation' in the ioctl description.

Thanks.
