### ISSUE TITLE
Improve command line parsing

### ISSUE THREAD

**Issue by sboeuf** [intel/cloud-hypervisor#31]
Instead of performing the command line parsing from the `DeviceManager`, the parsing of the options and their validity should happen as soon as possible, hence this should be done right after the parameters have been retrieved.

This will allow us to build a structure containing all the configurations that can be needed by the `Vm` and the `DeviceManager`. One example of this, the `Vm` needs to know if the guest memory needs to be backed by a file, and this is directly tied to the fact that the user might ask for a vhost-user device. That's why after the parameters parsing, we should have all the information we need to know how to run the VM.

**Comment by sameo** [comment]
@sboeuf Could you elaborate on *performing the command line parsing from the DeviceManager* ?

**Comment by sboeuf** [comment]
@sameo yes the problem is that we should parse and validate what is passed by the user as the first thing. If you look at https://github.com/intel/cloud-hypervisor/blob/master/vmm/src/vm.rs#L462 for instance, well we parse the input from the user too late.
We should decouple the part where the user input is parsed from the part where we provide the config to the Vm.
I'm working on this right now, and hopefully I'll submit something soon :)
