### ISSUE TITLE
PIO resource alignment 

### ISSUE THREAD

**Issue by liujing2** [intel/cloud-hypervisor#35]
https://github.com/intel/cloud-hypervisor/blob/e5e651895b73c0fb74f649c182285d63cf97aeb3/vm-allocator/src/system.rs#L65

@sameo 
What is the reason to set alignment as 0x400? When allocating PIO resource (e.g. 0xcf8), `available_range()`  got the `request_address != aligned_address` so return Err.

**Comment by sameo** [comment]
@liujing2 That is a bug indeed. Probably a copy paste from crosvm, but crosvm does not use the IO addresses allocator API at all.

Please send a PR for this.

**Comment by liujing2** [comment]
Sure. It needs to be aligned as 0x4, right?

**Comment by liujing2** [comment]
https://github.com/intel/cloud-hypervisor/pull/36 is submitted

**Comment by rbradford** [comment]
This was fixed by #36
