### ISSUE TITLE
Add VFIO support

### ISSUE THREAD

**Issue by sboeuf** [intel/cloud-hypervisor#4]
As described in the goals for this project, we want cloud-hypervisor VMM to support direct device assignment that's achieved through VFIO.

Tracked through PR #60 

TODO

* [x] Add VFIO bindings crate
* [x] Add VFIO API wrappers
* [x] Add VFIO PCI support 
* [x] Map device memory regions into the guest
* [x] Remap host interrupts to guest ones
* [x] Add VFIO integration test
* [x] Add VFIO documentation (usage and arch)

**Comment by zhenyw** [comment]
FYI. We're trying to add VFIO support for crosvm. https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/1580455/1
Original purpose is to be used for VFIO mdev device e.g Intel vGPU. Hopefully that work could be picked into cloud-hypervisor or rust-vmm as well. Note that current support is still considered as experimental.

**Comment by sboeuf** [comment]
@zhenyw oh this is great, thanks for pointing us to your code. Of course, this should be part of `rust-vmm`, so that both crosvm and cloud-hypervisor can benefit from it.

**Comment by sameo** [comment]
@zhenyw Yes, we'd love for VFIO to be a rust-vmm crate that we could consume from cloud-hypervisor. I opened a rust-vmm community issue for that:
https://github.com/rust-vmm/community/issues/57

Could you describe the design of your current crosvm patchset there?
As rust-vmm lacks a PCI crate, I think we could initially start by working on adding the content of your `vfio.rs` there.

**Comment by xiongzha** [comment]
When we implement VFIO in crosvm, we meet the following dependent feature which isn't supported in existing crates, so we should consider it in cloud-hypervisor early.
1. mmio space allocation, as crosvm doesn't reserve enough mmio and doesn't scan pci devices before resource allocation,  large mmio allocation is hard in crosvm. 
2. MSI/MSI-x support
3. VFIO call KVM service at runtime. this means the communication channel between kvm  crate and other crates.

**Comment by sboeuf** [comment]
@xiongzha oh thanks for raising this, I agree it's important if we can anticipate potential design issues that would prevent us from supporting VFIO.

>mmio space allocation, as crosvm doesn't reserve enough mmio and doesn't scan pci devices before resource allocation, large mmio allocation is hard in crosvm.

I think this one should be easily solved by `cloud-hypervisor` as the `SystemAllocator` has a large address space (currently 64GiB). The scanning part needs to be done obviously before to call into the `SystemAllocator`.

>MSI/MSI-x support

Of course, we want to support MSI/MSI-X :). We have an issue opened for this matter, as virtio-pci currently relies on pin based interrupts.

>VFIO call KVM service at runtime. this means the communication channel between kvm crate and other crates.

Can you elaborate on this one? I'm not quite sure to get the issue?

**Comment by xiongzha** [comment]
>VFIO call KVM service at runtime. this means the communication channel between kvm crate and other crates.
>Can you elaborate on this one? I'm not quite sure to get the issue?
Vfio call vmfd->create_device(), set_user_memory_region(), add_irq_route()  during guest is running,  when other device call vmfd->set_user_memory_region(), it should call vfio->MemMap() which add this memory region into iommu table also.  This means &mut vmfd should be passed into vfio, and &vfio fd should be passed into kvm(this is hard).  When sandbox is enabled, vfio device mode runs in child process, while kvm run in parent main process, the direct fd->fn() call couldn't success. Currently crosvm use MsgSocket to call each other's service.

**Comment by sameo** [comment]
Closed with PR #60
