### ISSUE TITLE
failed to start while using clear-29160-service-os.img

### ISSUE THREAD

**Issue by Cordius** [intel/cloud-hypervisor#414]
I tried to use the following cmdline to start a vm:
```bash
./sources/cloud-hypervisor/target/release/cloud-hypervisor \
     --kernel ./images/hypervisor-fw-0.2.3 \
     --disk path=./images/clear-29160-kvm.img \
    --console off \
    --serial tty \
    --cmdline "console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \
    --cpus 4 \
    --memory size=4096M \
    --net "tap=ich0,mac=a4:a1:c2:00:00:01,ip=192.168.4.2,netmask=255.255.255.0" \
          "tap=ich1,mac=a4:a1:c2:00:00:05,ip=10.0.1.2,netmask=255.255.255.0" \
    --rng \
    --device path=/sys/bus/pci/devices/0000:c5:00.0
``` 
but failed with a error:
```
failed to find EFI partition
```

It works well with clear-29160-kvm.img, I'm wondering what difference between the two images.

**Comment by sameo** [comment]
Thanks for the issue @Cordius 
Where did you get clear-29160-service-os.img  from?

**Comment by Cordius** [comment]
> Thanks for the issue @Cordius
> Where did you get clear-29160-service-os.img from?

```
https://download.clearlinux.org/releases/29160/clear/clear-29160-service-os.img.xz
```

**Comment by sameo** [comment]
So that's a legacy boot image, we don't support that at the moment. Any specific reason why you need the CL service OS image?

**Comment by Cordius** [comment]
> So that's a legacy boot image, we don't support that at the moment. Any specific reason why you need the CL service OS image?

No specific reason. I see the doc said that the project has been tested with clear linux, so I just download a image. 
Thanks for you explanation.
BTW, does this project support assign Nvidia gpu to the guest by vfio?

**Comment by sameo** [comment]
> BTW, does this project support assign Nvidia gpu to the guest by vfio?

We've mostly tested device pass-through with NICs and virtio PCI devices, not yet with GPUs. There's nothing in the code preventing us from working, please open an issue if it does not work for you.

**Comment by rbradford** [comment]
@Cordius We have pretty advanced VFIO support but cannot test every device option. If it doesn't work then we can work together to identify why. Here is a CL image that is known to work:  https://download.clearlinux.org/image/clear-31520-kvm.img.xz (the 'kvm' variant is easier to work with than the cloud version as it doesn't require cloud-init to setup.)
