### ISSUE TITLE
Investigate APIC message

### ISSUE THREAD

**Issue by rbradford** [intel/cloud-hypervisor#42]
When booting with multiple vcpus the following message reported by the kernel:

`[    0.002961] [Firmware Bug]: CPU1: APIC id mismatch. Firmware: 1 APIC: 3`

Let's investigate this whether this is a serious issue or not (the kernel still reports both vcpus in `/proc/cpuinfo`)

**Comment by andreeaflorescu** [comment]
We had the same problem in Firecracker.
Issue: https://github.com/firecracker-microvm/firecracker/issues/222
and PR: https://github.com/firecracker-microvm/firecracker/pull/223

**Comment by chao-p** [comment]
No worry, it's not serious. I knew the issue long time ago and the reason is we miss some CPUID leaves for 0BH.

**Comment by sboeuf** [comment]
@chao-p if you have some bandwidth, please assign the issue to yourself and fix it :)
Otherwise I can have a look, just let me know.
