### ISSUE TITLE
virtiofs documentation is not up to date

### ISSUE THREAD

**Issue by sameo** [intel/cloud-hypervisor#433]
From the [virtiofs document](https://github.com/intel/cloud-hypervisor/blob/master/docs/fs.md#the-daemon):

```
The cache=none option here is an important one as it tells the daemon not to try any memory mapping of the files, but instead to use the virtqueues to convey the files content. The support for the memory mapping of the files will be added later.
```

That's no longer the case, we do support DAX caching now.

Reported by @ericooper

**Comment by sameo** [comment]
@sboeuf Could you please have a look at that one?

**Comment by sboeuf** [comment]
Oh yes let me take care of this one :)

**Comment by ericooper** [comment]
The mount syntax has also changed in virtiofs 0.3: mount TAG /mnt

**Comment by sboeuf** [comment]
Yes it did, I'll update it too.
