### ISSUE TITLE
Docs: Add device model summary

### ISSUE THREAD

**Issue by egernst** [intel/cloud-hypervisor#437]
A summary document of supported paravirt devices and their backend implementation details would be very helpful for folks who are new to the project, or evaluating the VMM.

**Comment by sboeuf** [comment]
@rbradford @sameo 
I can tackle this one as I agree with @egernst it is important to clearly state what is supported by the VMM. Basically we need a place to kind of summarize what has been added by each release.
Where should I post this documentation? Should it be part of the README as a dedicated section `Device Model`, or a separate doc living under `docs/`?

**Comment by sameo** [comment]
On Fri, Nov 15, 2019 at 09:02:18AM -0800, Sebastien Boeuf wrote:
> @rbradford @sameo 
> I can tackle this one as I agree with @egernst it is important to clearly state what is supported by the VMM. Basically we need a place to kind of summarize what has been added by each release.
> Where should I post this documentation? Should it be part of the README as a dedicated section `Device Model`, or a separate doc living under `docs/`?
>

Probably as a standalone doc under docs/ and have it referenced from the
README.

**Comment by sboeuf** [comment]
Ok sounds good :+1:
