### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by konradwilk** [intel/cloud-hypervisor#59]
Your invite link in the README.md has expired:

https://join.slack.com/t/cloud-hypervisor/shared_invite/enQtNjE5MzU2OTU2NjU5LTllNzIzYzNmYTc2ZjA4Mjg2YWQ2M2Q0MzE3ZDk2NTVhMjIwZGIwYjE4NGY3YTI2MzU3NTBjNDJhYTNlMjdiMmM

**Comment by sboeuf** [comment]
Oh thanks for noticing. But I guess if we renew it, it's going to expire again at some point...
@sameo do you know if we can get some non-expiring slack invitation?

**Comment by sameo** [comment]
PR  #65 uses a permanent link.
